GOOGLE_DATE_FORMAT = "%y/%m/%d %H:%M:%S"
GOOGLE_VERSION_SHEETS = "v4"
GOOGLE_VERSION_DRIVE = "v3"
GOOGLE_SHEET_ID = 0
GOOGLE_TITLE_CLOSE_SPEED = "Время сбора средств."
GOOGLE_ROW_COUNT = 100
GOOGLE_COLUMN_COUNT = 11
GOOGLE_LOCALE = "ru_RU"
